/* casier.js */
const supabase=window.supabaseClient;let currentUser=null;document.addEventListener("DOMContentLoaded",async()=>{currentUser=await window.protegerPage();if(!currentUser)return;const emailElement=document.getElementById("userEmail");if(emailElement){emailElement.textContent=currentUser.email;}console.log("Utilisateur connecté :",currentUser.email);});document.getElementById("btnAjouter").addEventListener("click",async(e)=>{e.preventDefault();if(!currentUser){alert("Erreur : utilisateur non authentifié.");return;}const nom_rp=document.getElementById("nom_rp").value.trim();const grade_rp=document.getElementById("grade_rp").value;const regiment_rp=document.getElementById("regiment_rp").value;const steam_id=document.getElementById("steam_id").value.trim();const explication=document.getElementById("explication").value.trim();const sanction_appliquee=document.getElementById("sanction_appliquee").value.trim();const demande_sanction=document.getElementById("demande_sanction").value==="oui";const demande_sanction_texte=document.getElementById("demande_sanction_texte").value.trim();const infractionSelect=document.getElementById("infraction");const infraction=Array.from(infractionSelect.selectedOptions).map(opt=>opt.value);if(!nom_rp||!steam_id){alert("Merci de remplir au minimum NOM RP et SteamID.");return;}const{error}=await supabase.from("sanctions").insert([{nom_rp,grade_rp,regiment_rp,steam_id,infraction,explication,sanction_appliquee,demande_sanction,demande_sanction_texte,created_by:currentUser.email}]);if(error){console.error(error);alert("❌ Erreur lors de l'ajout.");}else{alert("✅ Sanction ajoutée !");document.getElementById("form-sanction").reset();}});document.getElementById("btnChercher").addEventListener("click",async(e)=>{e.preventDefault();const steam_id=document.getElementById("search_steam_id").value.trim();const zone=document.getElementById("zoneResultats");zone.innerHTML="";if(!steam_id){alert("Merci d'entrer un SteamID.");return;}const{data,error}=await supabase.from("sanctions").select("*").eq("steam_id",steam_id).order("created_at",{ascending:false});if(error){console.error(error);alert("❌ Erreur lors de la recherche.");return;}if(data.length===0){zone.innerHTML="<p>Aucun résultat trouvé.</p>";return;}data.forEach((row)=>{const card=document.createElement("div");card.classList.add("result-card");card.innerHTML=`
            <h3>${row.nom_rp} — ${row.grade_rp}</h3>
            <p><strong>Régiment :</strong> ${row.regiment_rp}</p>
            <p><strong>SteamID :</strong> ${row.steam_id}</p>
            <p><strong>Infractions :</strong> ${row.infraction.join(", ")}</p>
            <p><strong>Explication :</strong> ${row.explication}</p>
            <p><strong>Sanction appliquée :</strong> ${row.sanction_appliquee}</p>
            <p><strong>Demande de sanction :</strong> ${row.demande_sanction ? "Oui" : "Non"}</p>
            ${row.demande_sanction ? `<p><strong>Détail:</strong>${row.demande_sanction_texte}</p>` : ""}
            <p style="margin-top:10px; font-size:0.8em; color:#aaa;">
              Ajouté par : ${row.created_by || "Inconnu"}<br>
              Le : ${new Date(row.created_at).toLocaleString()}
            </p>
        `;zone.appendChild(card);});});document.getElementById("btnDAA").addEventListener("click",()=>{window.location.href="demandesanction.html";});
